quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=${ONBOARDING_DATASOURCE_JDBC_URL:jdbc:h2:file:/deployments/db/onboarding;DB_CLOSE_DELAY=-1}
quarkus.hibernate-orm.database.generation=${ONBOARDING_HIBERNATE_DATABASE_GENERATION:update}

token.service.client-secret=${TOKEN_SERVICE_CLIENT_SECRET}
